name: "web-ext Action for Firefox Add-ons"
author: "Philipp Kewisch <mozilla@kewis.ch>"
description: "Run a web-ext commmand"
branding:
  icon: "box"
  color: "gray-dark"
inputs:
  cmd:
    description: "The web-ext command to run (lint, build, sign)"
    required: true
  source:
    description: "The source xpi or path"
    required: false
    default: "."
  artifacts:
    description: "The path to put artifacts, e.g. from build or signing"
    required: false
    default: "web-ext-artifacts"
  verbose:
    description: "More debugging fore certain steps"
    required: false
    default: false
  channel:
    description: "[lint+sign] The target channel"
    required: false
    default: "unlisted"
  apiKey:
    description: "[sign] The API key used for signing"
    required: false
  apiSecret:
    description: "[sign] The API secret used for signing"
    required: false
  apiUrlPrefix:
    description: "[sign] The URL of the signing API, defaults to AMO production"
    required: false
    default: "https://addons.mozilla.org/api/v3"
  timeout:
    description: "[sign] The timeout for signing, default is 2 minutes"
    required: false
runs:
  using: "node12"
  main: "src/loader.js"
